name: MobAttacks
version: ${project.version}
main: com.monkey.mobattack.MobAttacks
api-version: '1.13'
authors: [ MonkeyMoon104 ]
description: Mob attack plugin

commands:
  mobattack:
    description: Main commands for MobAttack
    usage: /mobattack reload
    permission: mobattack.admin
    aliases:
      - mbreload

  warden:
    description: Unleash an attack like the Warden
    usage: /warden
    permission: mobattack.warden
    aliases:
      - wd

  creeper:
    description: Explode like a Creeper
    permission: mobattack.creeper
    aliases:
      - crpr

  ghast:
    description: Shoot a fireball like a Ghast
    permission: mobattack.ghast
    aliases:
      - gt
      - ght

  ravager:
    description: Charge forward like a Ravager
    permission: mobattack.ravager
    aliases:
      - rr
      - rgr
      - rvgr

  shulker:
    description: Shoot a levitating bullet like a Shulker
    permission: mobattack.shulker
    aliases:
      - sh
      - sk
      - slk
      - shlk

  blaze:
    description: Shoot 3 fireballs like a Blaze
    permission: mobattack.blaze
    aliases:
      - bz
      - blz

  evoker:
    description: Launch an Evoker-style fang attack
    usage: /evoker
    permission: mobattack.evoker
    aliases:
      - ek
      - evk

  wither:
    description: Shoot a Wither skull
    usage: /wither
    permission: mobattack.wither
    aliases:
      - wt
      - wth

  edragon:
    description: Shoot acid breath like the Ender Dragon
    usage: /edragon
    permission: mobattack.edragon
    aliases:
      - enderdragon
      - enderd
      - ed

  snowgolem:
    description: Throw a snowball like a Snow Golem
    usage: /snowgolem
    permission: mobattack.snowgolem
    aliases:
      - sgolem
      - snowg
      - sg

  enderman:
    description: Teleport behind the target like an Enderman
    usage: /enderman
    permission: mobattack.enderman
    aliases:
      - eman
      - em
      - enderm

  firebreath:
    description: Breathe fire in front of you!
    usage: /firebreath
    permission: mobattack.firebreath
    aliases:
      - fireb
      - fb
      - fbreath

permissions:
  mobattack.warden:
    default: op
  mobattack.admin:
    default: op
  mobattack.creeper:
    default: op
  mobattack.ghast:
    default: op
  mobattack.ravager:
    default: op
  mobattack.shulker:
    default: op
  mobattack.blaze:
    default: op
  mobattack.evoker:
    description: Allows use of the Evoker attack
    default: op
  mobattack.wither:
    description: Allows use of the Wither attack
    default: op
  mobattack.edragon:
    description: Allows use of the Ender Dragon attack
    default: op
  mobattack.snowgolem:
    description: Allows use of the Snow Golem attack
    default: op
  mobattack.enderman:
    description: Allows use of the Enderman teleport attack
    default: op
  mobattack.firebreath:
    description: Allows use of the Fire breath attack
    default: op